api:
  image:
    repository: abudev22/newtodo-api
    tag: latest
  replicaCount: 1
service:
  namespace: prod
ingress:
  host: api.production

db:
  image:
    repository: postgres
    tag: latest
  replicaCount: 1
  storage:
    size: 1Gi

config:
  dbEngine: "django.db.backends.postgresql"
  dbName: postgres
  dbUser: postgres
  dbHost: db-service
  dbPort: "5432"

secrets:
  dbPassword: postgres