apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: todo-helm
  namespace: prod
spec:
  interval: 1m
  url: https://github.com/Abudev22/todo-helm-cluster-pub
  ref:
    branch: main
    